### ISSUE TITLE
Есть ли возможность получить данные о количестве заказов любого товара?

### ISSUE THREAD

**Issue by edvard-munch** [Dakword/WBWebAPI#2]
В карточке товара таких данных не вижу. Но мб у вас есть варианты решения?

https://card.wb.ru/cards/v1/detail?appType=1&curr=rub&dest=-2228342&spp=27&nm=179850439

**Comment by topaspb** [comment]
> В карточке товара таких данных не вижу. Но мб у вас есть варианты решения?
> 
> https://card.wb.ru/cards/v1/detail?appType=1&curr=rub&dest=-2228342&spp=27&nm=179850439

Вам нужно использовать orderQnt

https://product-order-qnt.wildberries.ru/v2/by-nm/?nm=173512990,192560111,192741231,180290800,173514088,192741744,195275808,195276181,195277525,195275448

Но там максимальное значение 100000 потом данные не обновляются хз чего там программисты WB накосячили с полем.

**Comment by edvard-munch** [comment]
> > В карточке товара таких данных не вижу. Но мб у вас есть варианты решения?
> > https://card.wb.ru/cards/v1/detail?appType=1&curr=rub&dest=-2228342&spp=27&nm=179850439
> 
> Вам нужно использовать orderQnt
> 
> https://product-order-qnt.wildberries.ru/v2/by-nm/?nm=173512990,192560111,192741231,180290800,173514088,192741744,195275808,195276181,195277525,195275448
> 
> Но там максимальное значение 100000 потом данные не обновляются хз чего там программисты WB накосячили с полем.

**Comment by edvard-munch** [comment]
О, а я как раз раз сегодня нарыл этот url в JS скрпитах на страничке товара, ибо прямых XHR запросов на этот url нет
Но засомневался что это именно кол-во заказов. Там еще как-то странно что все значения кол-ва заказов округлены чтоли? Все цифры типа - 40, 100, 1900

Нет у вас идей как в том же сервисе Маяк реализован функционал по продажам за 30 дней? Вот ниже за 18 дней даже, обычно за 30 у них данные. Можно отслеживать остатки, но и новые поступления надо учитывать же, а как.

Вот этот товар, по нему тут 13 заказов за 18 дней. А в orderQnt всего 5 указано по данному артикулу, что-то не сходится у меня в голове.
![Screenshot from 2024-01-05 01-47-32](https://github.com/Dakword/WBWebAPI/assets/26732881/00348740-bfcb-45eb-b930-4643a1b09d1b)

Ладно, спасибо, на этом можно будет закрыть вопрос)

**Comment by topaspb** [comment]
> Вот этот товар, по нему тут 13 заказов за 18 дней. А в orderQnt всего 5 указано по данному артикулу, что-то не сходится у меня в голове.

Ну вот тут возникает вопрос откуда такие данные у Маяка если округление идет, либо им кто-то сливает данные какой-то трекер, либо они считают криво.
https://www.wildberries.ru/catalog/46825817/detail.aspx?targetUrl=SG вот тут какое число? Тот случай когда WB отдает только 100000
